name: DOD_Coverity_CI
on:
  schedule:
    - cron: "30 5 * * 3"
  workflow_dispatch:
jobs:
  Coverity_CPP: # Runs inside a container
    runs-on: dod_coverity
    container:
      image: artifactory.xilinx.com/aie-ipu-build-docker-local/aie-ipu-aiebuild-dod:0506
      options: --user z1aiebuild
      volumes:
      - /tools/batonroot/coverity/2022.3.0/:/tools/batonroot/coverity/2022.3.0/
      - /proj/aiebuilds/IPU/:/proj/aiebuilds/IPU/
      - /proj/coverity/vai_builds/:/proj/coverity/vai_builds/
    steps:
      - name: Checkout code
        run : |
          rm -rf DynamicDispatch
          git clone --recurse-submodules -b main https://gitenterprise.xilinx.com/VitisAI/DynamicDispatch.git
          cd DynamicDispatch
          git submodule update --init --recursive
      - name: Run  Build
        run: |
          source scl_source enable devtoolset-9 && \
          echo $0 && \
          echo "Running as: $(whoami)"
          cat /opt/xilinx/xrt/version.json && \
          source /opt/xilinx/xrt/setup.sh && \
          cd DynamicDispatch
          source setup.sh && \
          mkdir -p build && \
          printenv && \
          /tools/batonroot/coverity/2022.3.0/bin/cov-configure --template --compiler c++ --comptype g++ --version 9.3.1 --config /proj/coverity/vai_builds/coverity-config-dod-cpp.xml && \
          /tools/batonroot/coverity/2022.3.0/bin/cov-configure --template --compiler cc --comptype gcc --version 9.3.1 --config /proj/coverity/vai_builds/coverity-config-dod-cpp.xml && \
          /tools/batonroot/coverity/2022.3.0/bin/cov-build --config /proj/coverity/vai_builds/coverity-config-dod-cpp.xml --dir /proj/coverity/vai_builds/idir_dod_cpp_${{ github.run_number }} cmake -S . -B build -DCMAKE_INSTALL_PREFIX=build/Release -DENABLE_DD_TESTS=ON -DLOGGING_EN=ON -DUNIT_TEST_PERF_EN=ON && \
          cmake --build build --config=Release --target install --parallel
          /tools/batonroot/coverity/2022.3.0/bin/cov-analyze --cpp --dir /proj/coverity/vai_builds/idir_dod_cpp_${{ github.run_number }} -j 4 --all
          /tools/batonroot/coverity/2022.3.0/bin/cov-commit-defects --dir /proj/coverity/vai_builds/idir_dod_cpp_${{ github.run_number }} --host xsjcoverity01 --dataport 9090 --auth-key-file /proj/aiebuilds/IPU/Coverity/auth-key1.txt --stream dod_cpp --description dod_coverity_cpp_${{ github.run_number }}
        shell: bash
  Coverity_Python:
    runs-on: dod_coverity
    needs: [ Coverity_CPP ]
    steps:
      - name: Checkout code
        run : |
          rm -rf DynamicDispatch
          git clone --recurse-submodules -b main https://gitenterprise.xilinx.com/VitisAI/DynamicDispatch.git
          cd DynamicDispatch
          git submodule update --init --recursive
      - name: Setup Coverity for Python
        run: |
          cd $GITHUB_WORKSPACE
          echo "Github Workspace: $GITHUB_WORKSPACE"
          /tools/batonroot/coverity/2022.3.0/bin/cov-configure --python --config /proj/coverity/vai_builds/coverity_config_DOD_python.xml
          /tools/batonroot/coverity/2022.3.0/bin/cov-build --config /proj/coverity/vai_builds/coverity_config_DOD_python.xml --dir /proj/coverity/vai_builds/idir_dod_python_${{ github.run_number }} --no-command --fs-capture-search ./
          /tools/batonroot/coverity/2022.3.0/bin/cov-analyze --dir /proj/coverity/vai_builds/idir_dod_python_${{ github.run_number }} -j 4 --all
          /tools/batonroot/coverity/2022.3.0/bin/cov-commit-defects --dir /proj/coverity/vai_builds/idir_dod_python_${{ github.run_number }} --host xsjcoverity01 --dataport 9090 --auth-key-file /proj/aiebuilds/IPU/Coverity/auth-key1.txt --stream dod_python --description dod_coverity_python_${{ github.run_number }}
